{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kuard.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kuard.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: {{ .Values.ingress.limitConnections | quote }}
    nginx.ingress.kubernetes.io/limit-rps: {{ .Values.ingress.limitRps | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          #- path: /kuard(/|$)(.*)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}